# Generated by Django 6.0.5 on 2026-05-15 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_institucional', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('empresa', 'Empresa')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.OneToOneField(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_empresa', serialize=False, to='api.usuario')),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('descripcion_empresa', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('sector_economico', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.OneToOneField(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_estudiante', serialize=False, to='api.usuario')),
                ('carrera', models.CharField(db_column='Carrera', max_length=100)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('intereses', models.TextField(blank=True, null=True)),
                ('bloque_libre', models.TextField(blank=True, null=True)),
                ('ubicacion_tiempo_real', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id_empleo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_puesto', models.CharField(max_length=100)),
                ('tipo_empleo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horas_semana', models.CharField(blank=True, max_length=50, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('dias_laborales', models.CharField(blank=True, max_length=100, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='empleos', to='api.empresa')),
            ],
            options={
                'db_table': 'empleos',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_empleo', models.ForeignKey(db_column='id_empleo', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='api.empleo')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='api.estudiante')),
            ],
            options={
                'db_table': 'postulaciones',
                'unique_together': {('id_empleo', 'id_estudiante')},
            },
        ),
    ]
