# Generated by Django 6.0.5 on 2026-05-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
