# Generated by Django 6.0.5 on 2026-05-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='imagen_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
